USE ROLE CLEARPATH_AI_POC;
USE WAREHOUSE CLEARPATH_ETL_WH;
USE DATABASE CLEARPATH_AI_POC_DB;
USE SCHEMA CURATED_FINANCE;

-- =========================================================
-- STEP 3A - CURATED FINANCE VIEWS
-- Builds the AR, revenue, and aging views that feed
-- the Cortex Analyst semantic layer
-- =========================================================

-- Open AR by Invoice
CREATE OR REPLACE VIEW OPEN_ACCT_RECV_BY_INV_V AS
SELECT
    i.INVOICE_ID,
    i.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.REGION,
    c.INDUSTRY,
    c.PAYMENT_TERMS,
    i.INVOICE_DATE,
    i.DUE_DATE,
    i.AMOUNT                                              AS INVOICE_AMOUNT,
    COALESCE(SUM(p.PAYMENT_AMOUNT), 0)                   AS PAID_AMOUNT,
    i.AMOUNT - COALESCE(SUM(p.PAYMENT_AMOUNT), 0)        AS OPEN_AMOUNT,
    i.CURRENCY,
    i.STATUS                                              AS ERP_STATUS,
    i.INVOICE_DESCRIPTION,
    CASE
        WHEN i.AMOUNT - COALESCE(SUM(p.PAYMENT_AMOUNT), 0) <= 0 THEN 'PAID'
        WHEN CURRENT_DATE() > i.DUE_DATE                         THEN 'OVERDUE'
        ELSE 'OPEN'
    END AS AR_STATUS
FROM CLEARPATH_AI_POC_DB.RAW_FINANCE.INVOICE_RAW   i
JOIN CLEARPATH_AI_POC_DB.RAW_FINANCE.CUSTOMER_RAW  c ON i.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN CLEARPATH_AI_POC_DB.RAW_FINANCE.PAYMENT_RAW p ON i.INVOICE_ID = p.INVOICE_ID
GROUP BY
    i.INVOICE_ID, i.CUSTOMER_ID, c.CUSTOMER_NAME, c.REGION,
    c.INDUSTRY, c.PAYMENT_TERMS, i.INVOICE_DATE, i.DUE_DATE,
    i.AMOUNT, i.CURRENCY, i.STATUS, i.INVOICE_DESCRIPTION;


-- Revenue by Customer by Month
CREATE OR REPLACE VIEW CUSTOMER_REVENUE_MTH_V AS
SELECT
    r.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.REGION,
    c.INDUSTRY,
    DATE_TRUNC('MONTH', r.REVENUE_DATE)  AS REVENUE_MONTH,
    r.REVENUE_CATEGORY,
    SUM(r.REVENUE_AMOUNT)                AS REVENUE_AMOUNT
FROM CLEARPATH_AI_POC_DB.RAW_FINANCE.REVENUE_RAW  r
JOIN CLEARPATH_AI_POC_DB.RAW_FINANCE.CUSTOMER_RAW c ON r.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY
    r.CUSTOMER_ID, c.CUSTOMER_NAME, c.REGION, c.INDUSTRY,
    DATE_TRUNC('MONTH', r.REVENUE_DATE), r.REVENUE_CATEGORY;


-- AR Aging Buckets
CREATE OR REPLACE VIEW ACCT_RECV_AGING AS
SELECT
    INVOICE_ID,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    REGION,
    INDUSTRY,
    PAYMENT_TERMS,
    INVOICE_DATE,
    DUE_DATE,
    INVOICE_AMOUNT,
    PAID_AMOUNT,
    OPEN_AMOUNT,
    CURRENCY,
    ERP_STATUS,
    INVOICE_DESCRIPTION,
    AR_STATUS,
    DATEDIFF('DAY', DUE_DATE, CURRENT_DATE()) AS DAYS_PAST_DUE,
    CASE
        WHEN OPEN_AMOUNT <= 0                                                      THEN 'PAID'
        WHEN CURRENT_DATE() <= DUE_DATE                                            THEN 'CURRENT'
        WHEN DATEDIFF('DAY', DUE_DATE, CURRENT_DATE()) BETWEEN 1  AND 30           THEN '1-30'
        WHEN DATEDIFF('DAY', DUE_DATE, CURRENT_DATE()) BETWEEN 31 AND 60           THEN '31-60'
        WHEN DATEDIFF('DAY', DUE_DATE, CURRENT_DATE()) BETWEEN 61 AND 90           THEN '61-90'
        ELSE '90+'
    END AS AGING_BUCKET
FROM CLEARPATH_AI_POC_DB.CURATED_FINANCE.OPEN_ACCT_RECV_BY_INV_V;


-- Customer Balance Summary
CREATE OR REPLACE VIEW CUSTOMER_BALANCE_SUM_V AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    REGION,
    INDUSTRY,
    COUNT(*)                                                             AS INVOICE_COUNT,
    SUM(INVOICE_AMOUNT)                                                  AS TOTAL_INVOICED_AMOUNT,
    SUM(PAID_AMOUNT)                                                     AS TOTAL_PAID_AMOUNT,
    SUM(OPEN_AMOUNT)                                                     AS TOTAL_OPEN_AMOUNT,
    SUM(CASE WHEN AR_STATUS = 'OVERDUE' THEN OPEN_AMOUNT ELSE 0 END)    AS TOTAL_OVERDUE_AMOUNT
FROM CLEARPATH_AI_POC_DB.CURATED_FINANCE.OPEN_ACCT_RECV_BY_INV_V
GROUP BY CUSTOMER_ID, CUSTOMER_NAME, REGION, INDUSTRY;
