USE ROLE CLEARPATH_AI_POC;
USE WAREHOUSE CLEARPATH_ETL_WH;
USE DATABASE CLEARPATH_AI_POC_DB;
USE SCHEMA RAW_DOCS;

-- =========================================================
-- STEP 2B - STAGE AND TARGET TABLES
-- Creates the internal stage for invoice PDFs and
-- the downstream tables for parsed/extracted/chunked data
-- =========================================================

CREATE OR REPLACE STAGE INVOICE_STAGE_SSE
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Server-side encrypted stage for ClearPath invoice PDFs used by AI_PARSE_DOCUMENT';

CREATE OR REPLACE TABLE INVOICE_STAGE_FILE_REGISTRY (
    RELATIVE_PATH   STRING,
    SIZE_BYTES      NUMBER,
    LAST_MODIFIED   TIMESTAMP_TZ,
    ETAG            STRING,
    FILE_URL        STRING,
    REGISTERED_TS   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

USE SCHEMA CURATED_DOCS;

CREATE OR REPLACE TABLE INVOICE_PARSED (
    DOCUMENT_ID     STRING,
    RELATIVE_PATH   STRING,
    PARSED_JSON     VARIANT,
    PARSED_TEXT     STRING,
    PARSED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE INVOICE_EXTRACT (
    DOCUMENT_ID     STRING,
    RELATIVE_PATH   STRING,
    INVOICE_NUMBER  STRING,
    CUSTOMER_NAME   STRING,
    INVOICE_DATE    DATE,
    DUE_DATE        DATE,
    PAYMENT_TERMS   STRING,
    CURRENCY        STRING,
    TOTAL_DUE       NUMBER(12,2),
    PO_NUMBER       STRING,
    EXTRACTED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE INVOICE_CHUNK (
    CHUNK_ID        STRING,
    DOCUMENT_ID     STRING,
    RELATIVE_PATH   STRING,
    INVOICE_NUMBER  STRING,
    CUSTOMER_NAME   STRING,
    DUE_DATE        DATE,
    TOTAL_DUE       NUMBER(12,2),
    CHUNK_TYPE      STRING,
    CHUNK_INDEX     NUMBER,
    CHUNK_TEXT      STRING,
    EXTRACTED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
