USE ROLE CLEARPATH_AI_POC;
USE WAREHOUSE CLEARPATH_ETL_WH;
USE DATABASE CLEARPATH_AI_POC_DB;

-- 1. Confirm files exist on the SSE stage -- should be 30 rows
SELECT COUNT(*) AS STAGED_FILES
FROM DIRECTORY(@CLEARPATH_AI_POC_DB.RAW_DOCS.INVOICE_STAGE_SSE);

-- 2. Confirm parsed document rows -- should be 30 rows
SELECT COUNT(*) AS PARSED_DOCS
FROM CLEARPATH_AI_POC_DB.CURATED_DOCS.INVOICE_PARSED;

-- 3. Confirm extracted rows -- should be 30 rows
SELECT COUNT(*) AS EXTRACTED_DOCS
FROM CLEARPATH_AI_POC_DB.CURATED_DOCS.INVOICE_EXTRACT;

-- 4. Confirm chunk rows
SELECT COUNT(*) AS CHUNKS
FROM CLEARPATH_AI_POC_DB.CURATED_DOCS.INVOICE_CHUNK;

-- 5. Inspect extracted invoice fields
SELECT
    DOCUMENT_ID,
    INVOICE_NUMBER,
    CUSTOMER_NAME,
    INVOICE_DATE,
    DUE_DATE,
    TOTAL_DUE,
    PAYMENT_TERMS,
    PO_NUMBER
FROM CLEARPATH_AI_POC_DB.CURATED_DOCS.INVOICE_EXTRACT
ORDER BY INVOICE_NUMBER;

-- 6. Preview parsed text for a few invoices
SELECT
    DOCUMENT_ID,
    RELATIVE_PATH,
    LEFT(PARSED_TEXT, 1000) AS PARSED_TEXT_PREVIEW
FROM CLEARPATH_AI_POC_DB.CURATED_DOCS.INVOICE_PARSED
ORDER BY DOCUMENT_ID
LIMIT 5;

-- 7. Preview generated chunks
SELECT
    DOCUMENT_ID,
    CHUNK_INDEX,
    CHUNK_TEXT
FROM CLEARPATH_AI_POC_DB.CURATED_DOCS.INVOICE_CHUNK
ORDER BY DOCUMENT_ID, CHUNK_INDEX
LIMIT 20;
