USE ROLE CLEARPATH_AI_POC;
USE WAREHOUSE CLEARPATH_ETL_WH;
USE DATABASE CLEARPATH_AI_POC_DB;
USE SCHEMA CURATED_DOCS;

-- =========================================================
-- STEP 2D - PARSE INVOICE PDFs
-- Uses AI_PARSE_DOCUMENT to extract structured text
-- from all ClearPath invoice PDFs in the SSE stage
-- =========================================================

TRUNCATE TABLE INVOICE_PARSED;

INSERT INTO INVOICE_PARSED (
    DOCUMENT_ID,
    RELATIVE_PATH,
    PARSED_JSON,
    PARSED_TEXT
)
WITH parsed AS (
    SELECT
        REGEXP_SUBSTR(RELATIVE_PATH, '[^/]+$') AS DOCUMENT_ID,
        RELATIVE_PATH,
        AI_PARSE_DOCUMENT(
            TO_FILE('@CLEARPATH_AI_POC_DB.RAW_DOCS.INVOICE_STAGE_SSE', RELATIVE_PATH),
            OBJECT_CONSTRUCT('mode', 'LAYOUT')
        ) AS DOC_OBJ
    FROM DIRECTORY(@CLEARPATH_AI_POC_DB.RAW_DOCS.INVOICE_STAGE_SSE)
)
SELECT
    DOCUMENT_ID,
    RELATIVE_PATH,
    DOC_OBJ           AS PARSED_JSON,
    DOC_OBJ:content::STRING AS PARSED_TEXT
FROM parsed;

-- Verify
SELECT COUNT(*) AS PARSED_COUNT FROM INVOICE_PARSED;

SELECT RELATIVE_PATH
FROM DIRECTORY(@CLEARPATH_AI_POC_DB.RAW_DOCS.INVOICE_STAGE_SSE)
ORDER BY RELATIVE_PATH;

-- Test single document parse (update invoice ID as needed)
SELECT AI_PARSE_DOCUMENT(
    TO_FILE('@CLEARPATH_AI_POC_DB.RAW_DOCS.INVOICE_STAGE_SSE', 'INV-2001.pdf'),
    OBJECT_CONSTRUCT('mode', 'LAYOUT')
);
