USE ROLE CLEARPATH_AI_POC;
USE WAREHOUSE CLEARPATH_ETL_WH;
USE DATABASE CLEARPATH_AI_POC_DB;

SELECT *
FROM CLEARPATH_AI_POC_DB.CURATED_FINANCE.OPEN_ACCT_RECV_BY_INV_V
ORDER BY OPEN_AMOUNT DESC, INVOICE_ID
LIMIT 20;

SELECT *
FROM CLEARPATH_AI_POC_DB.CURATED_FINANCE.CUSTOMER_REVENUE_MTH_V
ORDER BY CUSTOMER_ID, REVENUE_MONTH;

SELECT *
FROM CLEARPATH_AI_POC_DB.CURATED_FINANCE.ACCT_RECV_AGING
ORDER BY DAYS_PAST_DUE DESC, OPEN_AMOUNT DESC
LIMIT 20;

SELECT *
FROM CLEARPATH_AI_POC_DB.CURATED_FINANCE.CUSTOMER_BALANCE_SUM_V
ORDER BY TOTAL_OPEN_AMOUNT DESC;

SELECT
    OVERALL_RECON_STATUS,
    COUNT(*) AS INVOICE_COUNT
FROM CLEARPATH_AI_POC_DB.CURATED_FINANCE.INVOICE_RECON_V
GROUP BY OVERALL_RECON_STATUS
ORDER BY OVERALL_RECON_STATUS;

-- Seeded mismatches: INV-2003 (qty), INV-2009 (price), INV-2023 (name), INV-2030 (terms)
SELECT
    INVOICE_ID,
    ERP_CUSTOMER_NAME,
    DOC_CUSTOMER_NAME,
    ERP_INVOICE_DATE,
    DOC_INVOICE_DATE,
    ERP_DUE_DATE,
    DOC_DUE_DATE,
    ERP_PAYMENT_TERMS,
    DOC_PAYMENT_TERMS,
    ERP_AMOUNT,
    DOC_AMOUNT,
    DOC_PO_NUMBER_STATUS,
    OVERALL_RECON_STATUS,
    RECON_EXCEPTION_DETAIL
FROM CLEARPATH_AI_POC_DB.CURATED_FINANCE.INVOICE_RECON_V
WHERE OVERALL_RECON_STATUS = 'MISMATCH'
ORDER BY INVOICE_ID;

SELECT
    INVOICE_ID,
    ERP_CUSTOMER_NAME,
    DOC_CUSTOMER_NAME,
    ERP_DUE_DATE,
    DOC_DUE_DATE,
    ERP_PAYMENT_TERMS,
    DOC_PAYMENT_TERMS,
    ERP_AMOUNT,
    DOC_AMOUNT,
    DOC_PO_NUMBER_STATUS,
    RECON_EXCEPTION_DETAIL
FROM CLEARPATH_AI_POC_DB.CURATED_FINANCE.INVOICE_RECON_V
WHERE INVOICE_ID IN ('INV-2003', 'INV-2009', 'INV-2023', 'INV-2030')
ORDER BY INVOICE_ID;

-- Match distribution by field
SELECT CUSTOMER_NAME_MATCH,  COUNT(*) AS CNT FROM CLEARPATH_AI_POC_DB.CURATED_FINANCE.INVOICE_RECON_V GROUP BY 1 ORDER BY 1;
SELECT INVOICE_DATE_MATCH,   COUNT(*) AS CNT FROM CLEARPATH_AI_POC_DB.CURATED_FINANCE.INVOICE_RECON_V GROUP BY 1 ORDER BY 1;
SELECT DUE_DATE_MATCH,       COUNT(*) AS CNT FROM CLEARPATH_AI_POC_DB.CURATED_FINANCE.INVOICE_RECON_V GROUP BY 1 ORDER BY 1;
SELECT PAYMENT_TERMS_MATCH,  COUNT(*) AS CNT FROM CLEARPATH_AI_POC_DB.CURATED_FINANCE.INVOICE_RECON_V GROUP BY 1 ORDER BY 1;
SELECT AMOUNT_MATCH,         COUNT(*) AS CNT FROM CLEARPATH_AI_POC_DB.CURATED_FINANCE.INVOICE_RECON_V GROUP BY 1 ORDER BY 1;

SELECT
    INVOICE_ID,
    CUSTOMER_NAME_MATCH, INVOICE_DATE_MATCH, DUE_DATE_MATCH,
    PAYMENT_TERMS_MATCH, CURRENCY_MATCH, AMOUNT_MATCH,
    DOC_PO_NUMBER_STATUS, OVERALL_RECON_STATUS, RECON_EXCEPTION_DETAIL
FROM CLEARPATH_AI_POC_DB.CURATED_FINANCE.INVOICE_RECON_V
ORDER BY INVOICE_ID;
