USE ROLE CLEARPATH_AI_POC;
USE WAREHOUSE CLEARPATH_APP_WH;
USE DATABASE CLEARPATH_AI_POC_DB;
USE SCHEMA SEARCH;

-- =========================================================
-- STEP 4A - CORTEX SEARCH SERVICE
-- Indexes ClearPath invoice chunks for semantic retrieval
-- including SKU line items, quantities, and pricing
-- =========================================================

CREATE OR REPLACE CORTEX SEARCH SERVICE INVOICE_SEARCH_SVC
ON CHUNK_TEXT
ATTRIBUTES
  DOCUMENT_ID,
  RELATIVE_PATH,
  CHUNK_TYPE,
  CHUNK_INDEX,
  INVOICE_NUMBER,
  CUSTOMER_NAME,
  DUE_DATE,
  TOTAL_DUE
WAREHOUSE = CLEARPATH_APP_WH
TARGET_LAG = '5 minutes'
INITIALIZE = ON_CREATE
AS
SELECT
    CHUNK_TEXT,
    DOCUMENT_ID,
    RELATIVE_PATH,
    CHUNK_TYPE,
    CHUNK_INDEX,
    INVOICE_NUMBER,
    CUSTOMER_NAME,
    DUE_DATE,
    TOTAL_DUE
FROM CLEARPATH_AI_POC_DB.CURATED_DOCS.INVOICE_CHUNK;

-- Verify
DESCRIBE CORTEX SEARCH SERVICE INVOICE_SEARCH_SVC;

SELECT *
FROM CLEARPATH_AI_POC_DB.INFORMATION_SCHEMA.CORTEX_SEARCH_SERVICES
WHERE SERVICE_NAME = 'INVOICE_SEARCH_SVC';

-- Test search (update invoice ID as needed)
SELECT SNOWFLAKE.CORTEX.SEARCH_PREVIEW(
    'CLEARPATH_AI_POC_DB.SEARCH.INVOICE_SEARCH_SVC',
    '{
        "query": "INV-2009 total amount due North Carolina DOT",
        "columns": ["DOCUMENT_ID", "RELATIVE_PATH", "CHUNK_TYPE", "CHUNK_INDEX", "INVOICE_NUMBER", "CUSTOMER_NAME", "DUE_DATE", "TOTAL_DUE"],
        "limit": 8
    }'
) AS SEARCH_RESULTS;

-- Spot-check chunks joining to extract
SELECT
    c.CHUNK_TEXT,
    c.DOCUMENT_ID,
    c.RELATIVE_PATH,
    c.CHUNK_INDEX,
    e.INVOICE_NUMBER,
    e.CUSTOMER_NAME,
    e.DUE_DATE,
    e.TOTAL_DUE
FROM CLEARPATH_AI_POC_DB.CURATED_DOCS.INVOICE_CHUNK   c
LEFT JOIN CLEARPATH_AI_POC_DB.CURATED_DOCS.INVOICE_EXTRACT e
  ON c.DOCUMENT_ID = e.DOCUMENT_ID
LIMIT 20;
